apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU= # Values must be base64 encoded --> echo -n 'username' | base64
  mongodb-root-password: cGFzc3dvcmQ=
